spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proposal_submitter_db
    username: root
    password: Gg7771999
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: default
jwt:
  publicKey: classpath:app.pub
  privateKey: classpath:app.key
---
spring:
  config:
    activate:
      on-profile: mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: jakub.badzioch.main@gmail.com
    password: znlnboojwymcyhkt
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

